/* Text to put at the beginning of the generated file. Probably a license. */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

 uint32_t add(uint32_t A) ;

 uint32_t add_array(const int32_t *BytsPtr, size_t BytsLen) ;

 uint32_t *ret_arr(void) ;

/* Text to put at the end of the generated file */
