/* Text to put at the beginning of the generated file. Probably a license. */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

typedef struct CAPI_ArrResult CAPI_ArrResult;

 uint32_t add(uint32_t A) ;

 uint32_t add_array(const uint32_t *BytsPtr, size_t BytsLen) ;

 struct CAPI_ArrResult *create_arr_result(void) ;

 CAPI_WatermarkTask *create_watermarktask(void) ;

 void destroy_arr_result(struct CAPI_ArrResult *Ptr) ;

 void destroy_watermarktask(CAPI_WatermarkTask *Ptr) ;

 uint32_t get_old_section_jpeg(CAPI_WatermarkTask *Ptr, struct CAPI_ArrResult *Target) ;

 uint32_t get_old_section_webp(CAPI_WatermarkTask *Ptr, struct CAPI_ArrResult *Target) ;

 uint32_t get_output_jpeg(CAPI_WatermarkTask *Ptr, struct CAPI_ArrResult *Target) ;

 uint32_t get_output_webp(CAPI_WatermarkTask *Ptr, struct CAPI_ArrResult *Target) ;

 struct CAPI_ArrResult *get_section_jpeg(const uint8_t *BytsPtr, size_t BytsLen, uint32_t X, uint32_t Y, uint32_t W, uint32_t H) ;

 struct CAPI_ArrResult *get_section_webp(const uint8_t *BytsPtr, size_t BytsLen, uint32_t X, uint32_t Y, uint32_t W, uint32_t H) ;

 size_t len_arr_result(struct CAPI_ArrResult *Ptr) ;

 uint32_t process_watermark(CAPI_WatermarkTask *Ptr) ;

 const uint8_t *read_arr_result(struct CAPI_ArrResult *Ptr, size_t Len) ;

 uint32_t *ret_arr(void) ;

 uint32_t set_key(CAPI_WatermarkTask *Ptr, const uint8_t *BytsPtr, size_t BytsLen) ;

 void set_position_watermark(CAPI_WatermarkTask *Ptr, uint32_t X, uint32_t Y, uint8_t OriginX, uint8_t OriginY) ;

 uint32_t set_target_jpeg(CAPI_WatermarkTask *Ptr, const uint8_t *BytsPtr, size_t BytsLen) ;

 uint32_t set_target_webp(CAPI_WatermarkTask *Ptr, const uint8_t *BytsPtr, size_t BytsLen) ;

 uint32_t set_watermark_jpeg(CAPI_WatermarkTask *Ptr, const uint8_t *BytsPtr, size_t BytsLen) ;

 uint32_t set_watermark_webp(CAPI_WatermarkTask *Ptr, const uint8_t *BytsPtr, size_t BytsLen) ;

/* Text to put at the end of the generated file */
